# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_criterion1 <- function(X, beta, z, y, eps1, eps2) {
    .Call(`_openFHDQR_check_criterion1`, X, beta, z, y, eps1, eps2)
}

check_criterion2 <- function(sigma, X, z, old_z, eps1, eps2, theta) {
    .Call(`_openFHDQR_check_criterion2`, sigma, X, z, old_z, eps1, eps2, theta)
}

l2_norm <- function(u) {
    .Call(`_openFHDQR_l2_norm`, u)
}

#' Perform proximal ADMM for weighted L1-penalized quantile regression
#'
#' @param beta0 initial value of beta
#' @param z0 initial value of z
#' @param theta0 initial value of theta
#' @param sigma sigma constant, a positive number
#' @param X design matrix
#' @param eta eta constant
#' @param y y vector
#' @param l1 L1 penalty parameter
#' @param l2 L2 penalty parameter
#' @param w weights vector for lambda1 penalty
#' @param nu weights vector for lambda2 penalty
#' @param tau quantile, a number between 0 and 1
#' @param gamma gamma constant, affects the step length in the theta update step
#' @param maxiter maximum number of iterations
#' @param eps1 epsilon1 constant for stopping
#' @param eps2 epsilon2 constant for stopping
#' @return beta, the vector of coefficient estimates
#' @export
padmm <- function(beta0, z0, theta0, sigma, X, eta, y, l1, l2, w, nu, tau, gamma, max_iter, eps1, eps2) {
    .Call(`_openFHDQR_padmm`, beta0, z0, theta0, sigma, X, eta, y, l1, l2, w, nu, tau, gamma, max_iter, eps1, eps2)
}

#' Soft shrinkage operator per Gu et al. 2018
#'
#' @param u a numeric vector of length one
#' @param alpha a numeric vector of length one
#' @return a numeric vector of length one, the output of the soft shrinkage operator
shrink <- function(u, alpha) {
    .Call(`_openFHDQR_shrink`, u, alpha)
}

#' Perform proximal mapping of rho tau
#'
#' @param xi a single number
#' @param alpha a number
#' @param tau a number between 0 and 1, the quantile of interest
#' @return output of the proximal mapping of rho tau
prox <- function(xi, alpha, tau) {
    .Call(`_openFHDQR_prox`, xi, alpha, tau)
}

choose_col <- function(x, idx) {
    .Call(`_openFHDQR_choose_col`, x, idx)
}

choose_row <- function(x, idx) {
    .Call(`_openFHDQR_choose_row`, x, idx)
}

choose_element <- function(x, ridx, cidx) {
    .Call(`_openFHDQR_choose_element`, x, ridx, cidx)
}

#' Update beta for the proximal ADMM for weighted elastic net-penalized quantile regression
#'
#' @param beta current state of the beta parameter vector
#' @param X design matrix
#' @param theta current state of theta vector
#' @param sigma sigma constant, numeric vector of length 1
#' @param eta eta constant, numeric vector of length 1
#' @param y outcome vector
#' @param z current state of z vector
#' @param l1 lambda1 penalty parameter
#' @param l2 lambda2 penalty parameter
#' @param w weights vector for L1 penalty
#' @param nu weights vector for L2 penalty
#' @return updated beta vector
#' @family proximal ADMM for weighted L1 penalized quantile regression
update_beta_padmm <- function(beta, X, theta, sigma, eta, y, z, l1, l2, w, nu) {
    .Call(`_openFHDQR_update_beta_padmm`, beta, X, theta, sigma, eta, y, z, l1, l2, w, nu)
}

update_theta_diff <- function(gamma, sigma, X, beta, z, y) {
    .Call(`_openFHDQR_update_theta_diff`, gamma, sigma, X, beta, z, y)
}

#' Update z for the proximal ADMM or scd ADMM for weighted L1-penalized quantile regression
#'
#' @param y y vector
#' @param X design matrix
#' @param beta beta vector
#' @param theta current state of theta parameter vector (k)
#' @param sigma sigma constant
#' @param tau quantile, a number between 0 and 1
#' @return updated z vector
#' @family proximal ADMM for weighted L1 penalized quantile regression
update_z <- function(y, X, beta, theta, sigma, tau) {
    .Call(`_openFHDQR_update_z`, y, X, beta, theta, sigma, tau)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_openFHDQR_RcppExport_registerCCallable', PACKAGE = 'openFHDQR')
})
