# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Soft shrinkage operator per Gu et al. 2018
#'
#' @param u a numeric vector of length one
#' @param alpha a numeric vector of length one
#' @return a numeric vector of length one, the output of the soft shrinkage operator
shrink <- function(u, alpha) {
    .Call(`_openFHDQR_shrink`, u, alpha)
}

#' Perform proximal mapping of rho tau
#'
#' @param xi a single number
#' @param alpha a number
#' @param tau a number between 0 and 1, the quantile of interest
#' @return output of the proximal mapping of rho tau
prox <- function(xi, alpha, tau) {
    .Call(`_openFHDQR_prox`, xi, alpha, tau)
}

#' Update beta for the proximal ADMM for weighted L1-penalized quantile regression
#'
#' @param beta current state of the beta parameter vector
#' @param X design matrix
#' @param theta current state of theta vector
#' @param sigma sigma constant, numeric vector of length 1
#' @param eta eta constant, numeric vector of length 1
#' @param y outcome vector
#' @param z current state of z vector
#' @param lambda lambda penalty parameter
#' @param w weights vector
#' @return updated beta vector
#' @family proximal ADMM for weighted L1 penalized quantile regression
#' @export
update_beta_padmm <- function(beta, X, theta, sigma, eta, y, z, lambda, w) {
    .Call(`_openFHDQR_update_beta_padmm`, beta, X, theta, sigma, eta, y, z, lambda, w)
}

#' Update theta for the proximal ADMM or scd ADMM for weighted L1-penalized quantile regression
#'
#' @param theta current state of theta (k)
#' @param gamma gamma constant
#' @param sigma sigma constant
#' @param X design matrix
#' @param beta current state of beta, (k + 1)
#' @param z current state of z, (k + 1)
#' @param y y vector
#' @return updated theta vector
#' @export
NULL

update_theta <- function(theta, gamma, sigma, X, beta, z, y) {
    .Call(`_openFHDQR_update_theta`, theta, gamma, sigma, X, beta, z, y)
}

#' Update z for the proximal ADMM or scd ADMM for weighted L1-penalized quantile regression
#'
#' @param y y vector
#' @param Xbeta matrix product of X and beta
#' @param theta current state of theta parameter vector (k)
#' @param sigma sigma constant
#' @param tau quantile, a number between 0 and 1
#' @return updated z vector
#' @family proximal ADMM for weighted L1 penalized quantile regression
#' @export
update_z <- function(y, Xbeta, theta, sigma, tau) {
    .Call(`_openFHDQR_update_z`, y, Xbeta, theta, sigma, tau)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_openFHDQR_RcppExport_registerCCallable', PACKAGE = 'openFHDQR')
})
