# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shrink <- function(u, alpha) {
    .Call(`_openFHDQR_shrink`, u, alpha)
}

prox <- function(xi, alpha, tau) {
    .Call(`_openFHDQR_prox`, xi, alpha, tau)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_openFHDQR_RcppExport_registerCCallable', PACKAGE = 'openFHDQR')
})
